### ISSUE TITLE
File I/O vs User Input

### ISSUE THREAD

**Issue by etoumey** [jtoumey/tss_estimator#5]
If we take input straight from file using 
<code> ./a.out < GPXFILE.gpx </code>
How do we make sure the user can still input threshold HR?

OR, could threshold HR be hard-coded? User specific, but it stays the same right? Maybe slight variation with fitness

**Comment by etoumey** [comment]
If we hard-code threshold HR, we can dump the "get_input" function. Don't need it anymore. File name is taken care of.

Less room for code breaking

**Comment by jtoumey** [comment]
1. I do not know if accepting an input file name from the command line and requesting user input from within the program via `scanf` will work. Maybe the code will still support reading the LTHR from `scanf()`. Not sure... I can try and test this later. 
2. I have a problem with hard-coding HR for anything other than testing. It is user-specific, like you said, and generally it changes (and should be re-tested) throughout a season... 
3. Also -- I totally agree that removing _get_input_ function means less room for code breaking (especially since we have so many problems in there right now). On the other hand, I like the robustness of being able to accept user input, especially if other people want to use this (I know some on my team who might).

**Comment by etoumey** [comment]
Fair enough.

I will think about it some more. I have some bash script to open the most recent file from a directory. That way it could just snag the most recent file from a directory of GPX files. This is all to dodge the hyphen issue. But no room for LTHR input. maybe there's a way in bash to handle that. What do you think about that?

**Comment by jtoumey** [comment]
I think that's a good idea. Grabbing the most recent file would be super convenient. 

I do have one issue -- again, for robustness, it would be great if all file handling was contained within the C program. Giving people a bash script and a program isn't as portable and gives more places for something to break. 

My approach is that maybe some day we will be able to share this program, and because of this, we should focus on usability... but there's definitely a trade-off (since I've spent 3 days figuring out how to get input the way I want, LOL). 

What if we proceed with your bash method and focus on main part of the program -- parsing/analyzing HR? Then, later, we can figure out a self-contained input method...

**Comment by etoumey** [comment]
Yeah. That sounds fine. Here's a thought: instead of passing the whole file in, we can just pass the file name. In the form ./a.out filename.gpx hard-code that as "TestGPX.gpx" for now. Then in the part of the prog that does the calculations, we can <code> fopen(*filename) </code>
